
import { GoogleGenAI, Modality } from "@google/genai";
import type { Student } from '../types';
import { PROFESSIONS, BACKGROUNDS, STYLES, AGES } from '../constants';

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

function constructPrompt(student: Student): string {
  const profession = PROFESSIONS.find(p => p.id === student.profession);
  const style = STYLES.find(s => s.id === student.style);
  const background = BACKGROUNDS.find(b => b.id === student.background);
  const ageInfo = AGES.find(a => a.id === student.age);
  
  let prompt = `A ${style?.name || 'realistic'} portrait of a young Vietnamese student, preserving their exact facial features from the provided image.`;

  if (ageInfo) {
    if (ageInfo.id === 'auto') {
      prompt += ` The student's age in the generated image should match the estimated age from the original photo.`;
    } else {
      prompt += ` The student should be depicted as being in the ${ageInfo.name} age range.`;
    }
  }

  if (profession) {
    prompt += ` The student is dressed as a ${profession.name}, wearing: ${profession.description}.`;
  }

  if (student.style === 'realistic') {
    prompt += ` The student should have a friendly, cute, or cool expression, making the portrait feel warm and positive.`;
  }

  if (background) {
    if (background.id === 'contextual') {
      prompt += ` The background should be a contextually appropriate setting for the profession.`;
    } else {
      prompt += ` The background is a solid color: ${background.name.split(': ')[1]}.`;
    }
  }

  if(student.aspectRatio !== '1:1') {
      prompt += ` The aspect ratio should be ${student.aspectRatio}.`
  }
  
  if (student.specialRequest) {
    prompt += ` Additional details: ${student.specialRequest}.`;
  }

  prompt += ` The final image should be high quality and detailed. Critically, there must be absolutely no text, letters, or numbers visible anywhere in the image.`;

  return prompt;
}

export const generateImage = async (student: Student): Promise<string> => {
  if (!student.originalImage) {
    throw new Error('Original image is required for generation.');
  }

  const prompt = constructPrompt(student);
  
  const imagePart = {
    inlineData: {
      data: student.originalImage.base64,
      mimeType: student.originalImage.mimeType,
    },
  };
  
  const textPart = {
    text: prompt
  };
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
        parts: [
          imagePart,
          textPart
        ]
    },
    config: {
        responseModalities: [Modality.IMAGE],
    }
  });

  for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
          return part.inlineData.data;
      }
  }

  throw new Error('No image was generated by the API.');
};
